### PR TITLE
Update everything

### PR DESCRIPTION
**Pull request by michikrug**
Since I was asked to update pgoapi to the latest changes, here it is...

Feel free to request changes!

**List of changes:**

- add locale parameter

_based on aiopogo:_
- update auth class
- update PTC login flow

_based on @sebastienvercammen changes:_
- integrate RPC_ID generation
- reformat some files

### CODE REVIEW

**Comment by michikrug** [comment]
Does anybody know about:
protos/pogoprotos/networking/platform/requests/plat_eight_request_pb2.py
protos/pogoprotos/networking/platform/responses/plat_eight_response_pb2.py

Since I have somehow merged them sometime and I do not know if they should be there.

**Comment by FrostTheFox** [comment]
```based on aiopogo:
update PTC login flow```
^ Wording here is a little misleading. The flow itself wasn't updated, just the code around it.

Also, the headers are *mostly* good, I would update the UA to a more modern one (optional). Also, Accept-Encoding is missing a value. Refer to my MITM: https://pst.fur.pm/yiyaxelimo.http

**Comment by michikrug** [comment]
Well the URLs called / the order changed...

Thanks for the hints. I will have a look at the MITM.

**Comment by FrostTheFox** [comment]
Apologies, I must have confused some tabs when I was reviewing last night. The header part is still valid :)

**Comment by michikrug** [comment]
Messed up the branch somehow.

Now please see #221

**Pull request closed without merging**
