### PR TITLE
Update to newest protos

### PR DESCRIPTION
**Pull request by Noctem**
Update protos with some fixes and new names, adjust to new names in the updated protos and the new procedure for packing the encrypted signature, change `altitude` to `accuracy` and select from a list instead of hardcoding (and make `altitude` optional), remove obsolete `_build_main_request_orig` function, and some cleaning of whitespace and comments.

### CODE REVIEW

**Comment by Noctem** [comment]
The protos are the latest git master + this PR pogodevorg/POGOProtos#13, I experienced errors without reverting those ints to unsigned.

**Comment by keyphact** [comment]
Seems like we've got conflicts @Noctem , are you able to resolve?

**Comment by Noctem** [comment]
@keyphact Yeah, mine also solved what #123 fixed. But the conflict is gone.

**Comment by vosk** [comment]
Running for 10-20 minutes now, without errors.

**Pull request merged**
