### PR TITLE
Implement a proper login HTTP sequence

### PR DESCRIPTION
**Pull request by ibuckshot5**
(It took all my will to not call this `BACK UP THE TRAIN WE FUCKED EVERYTHING UP`)

Apparently the login sequence is wrong, this implements a proper fix

### CODE REVIEW

**Comment by ibuckshot5** [comment]
Crap, forgot to commit this to `develop` branch, ah well.

**Comment by nullpixel** [comment]
Fixed

**Comment by ibuckshot5** [comment]
Thanks

**Comment by nullpixel** [comment]
nvm, this PR is messed up

**Pull request closed without merging**
