### PR TITLE
Added support for Google Two Factor Auth

### PR DESCRIPTION
**Pull request by gman-php**
The Google Auth module is missing support for Two Factor Auth. If your account has it enabled, you would simply get the standard error which would lead the user thinking his email/password combination was wrong. With this special exception you can catch that and display a proper error message that the user needs to make use of Google App Passwords: https://support.google.com/accounts/answer/185833?hl=en&ctx=ch_b%2F0%2FSmsAuthSettings

### CODE REVIEW

**Comment by gman-php** [comment]
Of course! Thanks for merging! :)

**Comment by n2o** [comment]
Thanks for this pull request! It fixes my problem and I am now able to login again. Currently I am referencing to your personal repository for the latest version, since this has been merged.

**Comment by nullpixel1** [comment]
Closing, since all it does is add an exception. Thanks for contributing nonetheless

**Comment by gman-php** [comment]
It also adds a check for this and returns this exception with the redirect URL included.
I would appreciate if you merge and commit it, as this is the only way to inform users with 2fa that they need an app password

**Comment by j16sdiz** [comment]
This should be rebased before merging.

**Comment by gman-php** [comment]
Is there anything I need to do here?
Afaik you can rebase when merging this; I actually also have no idea how rebase works; never done. So if you want me to do it, any help would be appreciated!

**Comment by gman-php** [comment]
Again: Anything I can do here? If I should rebase this, would appreciate some guidance what to actually do, as I'm unexperienced with rebase :) Thanks!

**Comment by gman-php** [comment]
Closed as this should go into develop. Created new PR for this: https://github.com/pogodevorg/pgoapi/pull/213

**Comment by krohne** [comment]
Reopen? I'm getting RPC 100 on master branch at 2017-OCT-11 commit. Using an hash key I just bought, and a new app password, just in case.

**Comment by ZeChrales** [comment]
Hi khrone you need to use /develop for now.

**Comment by krohne** [comment]
Now getting a 403 error from Google login, even with a new app password (twice). Tried API versions 6702, 6900, 7100, and 7500. Is there a magic API version number that works on dev branch?

**Pull request closed without merging**
