### PR TITLE
Update hashing for 0.45.0

### PR DESCRIPTION
**Pull request by Noctem**
Update hashing libs, update hash seed and U25, standardize library naming.

Linux compilation:
```bash
gcc -O3 -fPIC -shared niahash.c -o libniantichash-linux-x86-64.so
gcc -m32 -O3 -fPIC -shared niahash.c -o libniantichash-linux-i386.so
```
macOS compilation:
```bash
clang -march=core2 -shared -fPIC -mmacosx-version-min=10.7 -O3 niahash.c -o libniantichash-macos-x86-64.dylib
clang -m32 -shared -fPIC -mmacosx-version-min=10.5 -O3 niahash32.c -o libniantichash-macos-i386.dylib
```

Windows compilation:
```bash
x86_64-w64-mingw32-gcc -O3 -fPIC -shared niahash.c -o libniantichash-windows-x86-64.dll
i686-w64-mingw32-gcc -O3 -fPIC -shared niahash32.c -o libniantichash-windows-i686.dll
```

FreeBSD compilation:
```bash
clang -shared -fPIC -O3 niahash.c -o libniantichash-freebsd-x86-64.so
clang -m32 -shared -fPIC -O3 niahash32.c -o libniantichash-freebsd-i386.so
```

ARM compilation:
```bash
aarch64-linux-gnu-gcc -O3 -fPIC -shared niahash.c -o libniantichash-linux-arm64.so
arm-linux-gnueabihf-gcc -O3 -fPIC -shared niahash32.c -o libniantichash-linux-arm32.so
```

I have only tested this on macOS.

### CODE REVIEW

**Comment by FrostTheFox** [comment]
I'll try to test for windows.

**Comment by popcornmix** [comment]
This should be an arm32 version:
https://www.dropbox.com/s/wjbvdgqy0konxc9/libniantichash-linux-arm-32.so?dl=0
Using this source:
https://gist.github.com/popcornmix/a0804dd9f871c17a823ee377befc70c8

**Comment by FrostTheFox** [comment]
Windows is working a-ok for me 👍

**Comment by nullpixel1** [comment]
+1. Might need to move repo's so we can checksum them

**Comment by Noctem** [comment]
@nullpixel1 Noctem/pokecrypt-pgoapi@a9a36903277fc0f0fa31827eff8f166b127417ff is ready to go if we're doing that.

**Comment by keyphact** [comment]
Will accept this as breaking change for v.0.45.0-alpha, someone will need to update refs for: https://github.com/pokelibs/pgoapi-libs

**Comment by baskettcase** [comment]
For CentOS 6 I needed to run this to get it to work since the supplied file used glib 2.14 which Centos 6 doesn't look like it has.

gcc -O3 -fPIC -shared -std=c99 niahash.c -o libpcrypt-linux-x86-64.so

**Pull request merged**
